# Generated by Django 5.0 on 2024-08-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_channel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='channel_id',
            new_name='channelId',
        ),
    ]
