# Generated by Django 5.0 on 2024-08-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_channel_id_post_channelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='サムネイル'),
        ),
    ]
