# Generated by Django 5.0 on 2024-08-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latest_videos',
            field=models.JSONField(blank=True, null=True, verbose_name='最新動画'),
        ),
    ]
