# Generated by Django 5.0 on 2024-08-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_latest_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uid',
            field=models.CharField(blank=True, max_length=36, unique=True, verbose_name='uid'),
        ),
    ]
