# Generated by Django 5.0 on 2024-08-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_post_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='channelId',
        ),
        migrations.AddField(
            model_name='post',
            name='twitchChannelId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TwitchチャンネルID'),
        ),
        migrations.AddField(
            model_name='post',
            name='youtubeChannelId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='YouTubeチャンネルID'),
        ),
    ]
