# Generated by Django 5.0 on 2024-08-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_post_channelid_post_twitchchannelid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='twitchChannelId',
        ),
        migrations.RemoveField(
            model_name='post',
            name='youtubeChannelId',
        ),
        migrations.AddField(
            model_name='post',
            name='channelId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='チャンネルID'),
        ),
    ]
